apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: dreadful-skunk-python 
  janus-idp.io/tekton: dreadful-skunk-python
  backstage.io/kubernetes-id: dreadful-skunk-python
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: dreadful-skunk-python
resources: 
- application-dev.yaml 
- application-stage.yaml 
- application-prod.yaml  